### ISSUE TITLE
Add login support

### ISSUE THREAD

**Issue by msciabarra** [nuvolaris/nuvolaris#105]
Implement the `/api/v1/web/whisk-system/nuv/login`

it will receive a post with:

```
{
   "login": <login>
   "password": <password>
}
````

and return all the secrets to access the various components

```
{ 
  "AUTH": "xxx", 
  "REDIS_URL": "xxx"
  "MONGODB": xxx
}
```

The operator should read the configuration, then add in the database entries to store users.

Then it should generate and deploy an action that can read the users from the database, check for the password and return the corresponding key.

There is some starting code here:

https://github.com/nuvolaris/nuvolaris-operator/tree/main/actions

For this task, do de deployment of the login action manually with a task.

Probably the action should be generated to include the secrets to read and write the database at the administrative level, and avoid the secrets can be read with `wsk action get whisk-system/nuv/login`

We will add the deployment in the dbinit task.

**Comment by francescotimperi** [comment]
I assume that entries in the user database should be added every time there is a new whisk-user deployed similar to this

```
apiVersion: nuvolaris.org/v1
kind: WhiskUser
metadata:
  name: franztt
  namespace: nuvolaris
spec: 
  email: francesco@nuvolaris.io
  password: 51b64cd0-d765-419e-990d-d7dd30d7b68f:vPtIjR2MFMlYY7U5BY6N7TTogZXnJa8cl6ygPGnJIXOJonfA6MuNpVAdLN7m8iVc
  namespace: franztt
  redis:
    enabled: true
    prefix: ftt
    password: fttredispwd
  object-storage:        
    password: vPtIjR2MFMlYY7U5BY6N7TTogZXnJa8cl6ygPGnJIXOJonfA6MuNpVAdLN7m8iVc
    data:
      enabled: true
      bucket: franztt-data
    route:
      enabled: true
      host: localhost
      bucket: franztt-web
  mongodb:
    enabled: true
    database: ftt
    password: ahfdajsfdafdasffdasdja
```

In such sense can we assume that the login+password parameters for the action `/api/v1/web/whisk-system/nuv/login` should match the namespace+password attributes of the above user specs?
