### ISSUE TITLE
implement a scheduler

### ISSUE THREAD

**Issue by msciabarra** [nuvolaris/nuvolaris#114]
the scheduler works invoking actions with an annotation like this: 'cron: "* * * * *"' according the cron standard (every minute, at give minutes in the hours, every day and so on)

the implementation should be this way:

add to the [nuvolaris-operator](https://github.com/nuvolaris/nuvolaris-operator) codebase a './cron.sh' command (in python) that will access the database, identify the actions that should be invoked at the current date and time and invoke them. Note the library nuvolaris/couchdb.py that makes easy accessing the couchdb database.

You should activate the schedule.sh periodically with a cronjob like this:

```
apiVersion: batch/v1
kind: CronJob
metadata:
  name: hello
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: hello
            image: ghc.io/nuvloaris/nuvolaris-operator:xxx
            imagePullPolicy: IfNotPresent
            command:
            - /bin/sh
            - -c
            - ./cron.sh
          restartPolicy: OnFailure
```
