### ISSUE TITLE
define the crd to deploy a new user

### ISSUE THREAD

**Issue by msciabarra** [nuvolaris/nuvolaris#148]
The format should be this one:

```
 spec:
    email: <email>
    password: <password>
    namespaces: <namespace>
    redis:
       enabled: <flag>
       prefix: <prefix>
       password: <redis-password>
    s3:
       enabled: <flag>
       bucket: <bucket>
       password: <s3-password>
    mongodb:
        enabled: <flag>
        database: <database> 
        password: <mongodb-password>
    route: 
       enabled: <flag>
       host: <hostname>
```

also add the detection login that will trigger deployment of resources (separated tickets)

**Comment by francescotimperi** [comment]
What do we really mean by "detection login that will trigger deployment of resources (separated tickets)"?

For the CRD spec maybe we should use something like this, to avid using s3 which refers to a specific object-storage provider.

```
spec:
    email: <email>
    password: <password>
    namespaces: <namespace>
    redis:
       enabled: <flag>
       prefix: <prefix>
       password: <redis-password>
    object-storage:
       enabled: <flag>
       bucket: <bucket>
       password: <s3-password>
    mongodb:
        enabled: <flag>
        database: <database> 
        password: <mongodb-password>
    route: 
       enabled: <flag>
       host: <hostname>
```

and in case the object-storage is activated we will create 2 buckets <bucket>-data and <bucket>-web? Alternatively, as in  the other ticket referring to bucket creation we use <namespace>-data and <namespace>-web we can also remove the bucket attribute. Unless we will opt to create a bucket named <bucket> and tow subfolders <namespace>-data and <namespace>-web

**Comment by francescotimperi** [comment]
Final implementation decision/assumptions. 

We will deploy a new wsk.user CRD with spec as following

```
spec:
    email: <email>
    password: <password>
    namespace: <namespace>
    redis:
       enabled: <flag>
       prefix: <prefix>
       password: <redis-password>
    object-storage:
       enabled: <flag>
       bucket: <bucket>
       password: <s3-password>
    mongodb:
        enabled: <flag>
        database: <database> 
        password: <mongodb-password>
    route: 
       enabled: <flag>
       host: <hostname>
       password: <web-bucket-password>
       bucket: <bucket>
```

The implementation will provide a new python kopf based operator nuvolaris.user that will implement the deploy/undepoloy these components:

- a new OpenWhisk namespace by using the wskadmin tool to add a new `namespace/password` entry in the internal couch-DB
- a new bucket, which will be typically called, `namespace-data` if object-storage.enabled=true
- a new mondodb database, if mongodb.enabled=true
- a new object-storage bucket, typically called `namespace-web` to be used to serve static content and a specific NGINX-ingress route which will make accessible the static content exposing the given hostname over a https endpoint.
- a new redis database, if redis.enabled=true (the effective implementation still needs to be defined for multitenancy)
