### ISSUE TITLE
hide: Task "prereq" is up to date

### ISSUE THREAD

**Issue by msciabarra** [nuvolaris/nuvolaris#237]
I use the dependencies to avoid re-execute some commands.

Example:

```
prereq:
    silent: true
    cmds:
      - test -n "$AWS_SECRET_ACCESS_KEY" || die "please configure AWS with 'nuv config aws'"
      - aws --version  || die 'You need to install and configure aws cli tool before running this command.'
        || die 'Please generate or import the configured key  before continuing.'
      - "{{.SSH}} -V || die 'you need an ssh client in your PATH'"
      - config AWS_PREREQ_OK="true"
    status:
     - config AWS_PREREQ_OK
```

Unfortunately when a dependency is satisifed Tasks alwya displays "task: Task "prereq" is up to date"

Hack our fork to remove this message.
