### ISSUE TITLE
add support for CORS on api ingresses

### ISSUE THREAD

**Issue by francescotimperi** [nuvolaris/nuvolaris#351]
Under specific circumstancies applications may needs to submit request to openwhisk deployed actions using custom headers. As action are exposed over traffic or nginx ingresses there could be scenarios where the CORS is blocked because an header is not allowed.

We should add the possibility to customise the CORS  settings for both traefik and nginx ingresses. On traffic side this can be achieved using middleware similar to

```
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: xxxxxxx
  namespace: xxxxx
spec:
  headers:
      accessControlAllowMethods:
        - "*"
      accessControlAllowOriginList:
        - "*"
      accessControlAllowHeaders:
        - "Authorization"
        - "Origin"
        - "X-Requested-With"
        - "Content-Type"
        - "Accept"
        - "User-Agent"
        - "x-namespace-id"
      accessControlMaxAge: 100
      addVaryHeader: true
```

on infix ingress side it should be possible to configure it using

```
nginx.ingress.kubernetes.io/enable-cors | "true" or "false"
nginx.ingress.kubernetes.io/cors-allow-origin | string
nginx.ingress.kubernetes.io/cors-allow-methods | string
nginx.ingress.kubernetes.io/cors-allow-headers | string
nginx.ingress.kubernetes.io/cors-expose-headers | string
nginx.ingress.kubernetes.io/cors-allow-credentials | "true" or "false"
nginx.ingress.kubernetes.io/cors-max-age | number
```
